import Navbar from '../components/Navbar.jsx'
import Footer from '../components/Footer.jsx'
import React from 'react';
const Web3 = () => {
  return (
    <>
    <Navbar/>
    <div className="text-gray-800 dark:text-white px-[5%] md:px-[20%] py-8 md:py-16 bg-[#f0f8f0]  blog-light-bg dark:bg-[#252525]">
      <article
        id="10c85e8e-433c-809f-a0df-f32e6b0eb7a8"
        className="page sans"
      >
        <header className="flex flex-col items-center mb-8">
          <h1 className="text-5xl font-extrabold mb-2">WEB 3.0 : New Age Internet</h1>
          <img
            className="mt-4 rounded w-100 h-64 mb-4"
            src="/assets/blockchain.webp"
            alt="Blockchain"
          />
          <p className="page-description text-gray-600 dark:text-gray-400"></p>
        </header>
        <div className="page-body">
          <p className="mb-4 etherium.png font-bold">
            <strong className='text-2xl italic'>WEB 1.0 vs WEB 2.0 vs WEB 3.0</strong>
          </p>
          <div className="indented mb-4">
            <ul className="list-disc ml-5 mb-4">
              <li>What's the difference between these three?</li>
            </ul>
            <p className="mb-2">
              Yes, there’s so much to differentiate. Let's go back to history
              where people used websites to exchange information and view the
              content of the web. One can only view the content. So this{" "}
              <strong>web 1.0</strong> is where there is no interaction between
              website and user.
            </p>
            <p className="mb-2">
              Well, things took a turn around the 2000s. Web 2.0 is all about
              user interaction and dynamic content delivery. Websites became
              more <strong>interactive</strong> with users as contributors
              (comments, posts, shares). Driven by{" "}
              <strong>centralized platforms</strong> (e.g., Facebook, Google,
              YouTube, Twitter) that act as intermediaries between users and
              content. The majority of the internet is controlled by big-tech
              companies like Meta, Google, and Microsoft.
            </p>
            <p className="mb-2">
              The idea of being controlled frustrated many tech enthusiasts,
              driving the innovation of Blockchain, focusing on{" "}
              <strong>decentralization</strong>, <strong>blockchain technology</strong>, and <strong>cryptography</strong>. Here, it's all about digital identity where you own the data and control the data.
            </p>
            <p className="mb-2">
              WEB 1.0: Just Read the website (static).
            </p>
            <p className="mb-2">
              WEB 2.0: Read and write (dynamic).
            </p>
            <p className="mb-2">
              WEB 3.0: Read, Write, and Own.
            </p>
          </div>

          <h2 className="text-2xl font-bold mb-4">
            Blockchain Technology
          </h2>
          <p className="mb-4">
            Blockchain is not just about Bitcoin and Ethereum (two major
            blockchains); it is a network of decentralized computers,
            distributed all over the world, executing as one. No individual can
            control the behavior of the system. <strong>Blockchain</strong> is
            a <strong>decentralized and distributed digital ledger</strong>{" "}
            technology used to record transactions across multiple computers
            in a way that ensures <strong>security, transparency, and immutability</strong>. Once data is stored on a blockchain, it is not possible to delete it unless you control over 33% of total nodes in the network, which is not feasible in the real world.
          </p>

          <h3 className="text-xl font-bold mb-4">Technical View</h3>
          <div className="indented mb-4">
            <p className="mb-2">
              Blockchain is nothing but a chain of blocks, where each block
              stores new transactions along with the hash of the previous block
              and the block number. <strong>Blockhash</strong> is generated by
              applying cryptographic hash functions to all the transactional
              data. If anyone tries to modify a block, they need to change all
              the blocks after it, which is not possible because every blockchain
              maintains its consensus algorithms to handle fault tolerance.
            </p>
            <p className="mb-2">
              There are many prominent blockchains in today’s world. Some of
              these are <strong>Bitcoin, Ethereum, Solana</strong>, and so on.
              Each blockchain maintains its network of nodes and clients. Every
              blockchain implements its mechanism to communicate between the
              clients and nodes.
            </p>
          </div>

          <h2 className="text-2xl font-bold mb-4">
            Bitcoin: The Peer to Peer Electronic Cash System
          </h2>
          <div className="indented mb-4">
            <p className="mb-2">
              It is the first introduced blockchain, introduced by an anonymous
              person known as <strong>Satoshi Nakamoto</strong>. It aims to
              provide a decentralized alternative to traditional banks where
              users can transact currency without the need for banks. Bitcoin is
              a cryptocurrency that enables payments and transfers on the Bitcoin
              chain. New Bitcoin is generated by mining new blocks by miners.
              Miners try to solve cryptographic equations to receive newly
              generated Bitcoin. Bitcoin has a limited supply of 21 million, so
              it can't be inflated by introducing more bitcoins.
            </p>
            <figure
              id="10d85e8e-433c-806c-b195-c6b896d11404"
              className="image text-center mb-4"
            >
              <a href="">
                <img
                  className="mx-auto w-80"
                  src="/assets/bitcoin.png"
                  alt="Bitcoin"
                />
              </a>
            </figure>
          </div>

          <p className="mb-4">
            Blockchain primarily relies on cryptography to secure access to
            funds. Every user has an associated address (Public key), and a
            user can only send transactions using the private key associated
            with its public key. Blockchain stores the balances of every account
            on the network.
          </p>

          <h2 className="text-2xl font-bold mb-4">
            Ethereum: Next Generation Blockchain
          </h2>
          <div className="indented mb-4">
            <p className="mb-2">
              Ethereum is another prominent blockchain. Unlike Bitcoin, users
              can also build decentralized applications on Ethereum by deploying{" "}
              <strong>smart contracts</strong>. Smart contracts are programs
              users can interact with by sending transactions to the contract
              address. Smart contracts in Ethereum enable the transformation of
              many traditional financial systems into decentralized applications,
              such as decentralized lending platforms and decentralized
              exchanges.
            </p>
            <figure
              id="10d85e8e-433c-801e-b2f4-c63f7085734d"
              className="image text-center mb-4"
            >
              <a href="WEB%203%200%20New%20Age%20Internet%2010c85e8e433c809fa0dff32e6b0eb7a8/image%201.png">
                <img
                  className="mx-auto w-80"
                  src="/assets/etherium.png"
                  alt="Ethereum"
                />
              </a>
            </figure>
            <p className="mb-2">
              DeFi: Decentralized finance is gaining adoption in the Ethereum
              ecosystem, allowing users to rely on these decentralized systems
              without the need for a traditional banking system. Ether is the
              native currency of the Ethereum blockchain.
            </p>
          </div>

          <h2 className="text-2xl font-bold mb-4">Value Layer: Cryptocurrency</h2>
          <p className="mb-4">
            Blockchain and cryptocurrency are not the same; they represent
            different layers in the blockchain.
          </p>
          <p className="mb-4">
            Blockchain is the underlying technology facilitating the creation of
            a public ledger, while cryptocurrencies represent the value stored
            on the blockchain. A blockchain without cryptocurrencies cannot
            sustain itself in the long run. For instance, the Bitcoin blockchain
            stores the currency used for transactions, while Ethereum enables
            users to build and deploy decentralized applications using the Ether
            currency.
          </p>

          <h2 className="text-2xl font-bold mb-4">Conclusion</h2>
          <p className="mb-4">
            In conclusion, Web 3.0 represents the next generation of the web,
            built on the principles of decentralization, user control, and
            transparency. By leveraging blockchain technology, it empowers
            users to own their data and interact directly with applications
            without the need for intermediaries. The transition to Web 3.0 has
            the potential to revolutionize how we use the internet, fostering a
            more equitable and open digital landscape.
          </p>
        </div>
      </article>
    </div>
    <Footer/>
    </>
  );
};

export default Web3;